# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: argali_packet.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='argali_packet.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x13\x61rgali_packet.proto\"\xa2\x01\n\x07logline\x12\'\n\x05level\x18\x01 \x01(\x0e\x32\x11.logline.loglevel:\x05\x44\x45\x42UG\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"]\n\x08loglevel\x12\n\n\x06\x46ORCED\x10\x00\x12\t\n\x05\x46\x41TAL\x10\x01\x12\t\n\x05\x45RROR\x10\n\x12\x08\n\x04WARN\x10\x14\x12\x08\n\x04INFO\x10\x1e\x12\t\n\x05\x44\x45\x42UG\x10\x64\x12\x10\n\x0b\x44\x45\x42UG_NOISY\x10\xc8\x01\"f\n\x0b\x65\x63ho_packet\x12#\n\x03\x64ir\x18\x01 \x02(\x0e\x32\x16.echo_packet.direction\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"!\n\tdirection\x12\t\n\x05QUERY\x10\x00\x12\t\n\x05REPLY\x10\x01\"\xb1\x01\n\rargali_packet\x12\x30\n\x0cpayload_type\x18\x01 \x02(\x0e\x32\x1a.argali_packet.packet_type\x12\x1b\n\x07logline\x18\x02 \x01(\x0b\x32\x08.loglineH\x00\x12\x1c\n\x04\x65\x63ho\x18\x03 \x01(\x0b\x32\x0c.echo_packetH\x00\",\n\x0bpacket_type\x12\x0c\n\x08\x45\x43HO_PKT\x10\x00\x12\x0f\n\x0bLOGLINE_PKT\x10\x01\x42\x05\n\x03msg')
)



_LOGLINE_LOGLEVEL = _descriptor.EnumDescriptor(
  name='loglevel',
  full_name='logline.loglevel',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FORCED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FATAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=2, number=10,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='WARN', index=3, number=20,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INFO', index=4, number=30,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEBUG', index=5, number=100,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEBUG_NOISY', index=6, number=200,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=93,
  serialized_end=186,
)
_sym_db.RegisterEnumDescriptor(_LOGLINE_LOGLEVEL)

_ECHO_PACKET_DIRECTION = _descriptor.EnumDescriptor(
  name='direction',
  full_name='echo_packet.direction',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='QUERY', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='REPLY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=257,
  serialized_end=290,
)
_sym_db.RegisterEnumDescriptor(_ECHO_PACKET_DIRECTION)

_ARGALI_PACKET_PACKET_TYPE = _descriptor.EnumDescriptor(
  name='packet_type',
  full_name='argali_packet.packet_type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ECHO_PKT', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LOGLINE_PKT', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=419,
  serialized_end=463,
)
_sym_db.RegisterEnumDescriptor(_ARGALI_PACKET_PACKET_TYPE)


_LOGLINE = _descriptor.Descriptor(
  name='logline',
  full_name='logline',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='logline.level', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='logline.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LOGLINE_LOGLEVEL,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=186,
)


_ECHO_PACKET = _descriptor.Descriptor(
  name='echo_packet',
  full_name='echo_packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dir', full_name='echo_packet.dir', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='echo_packet.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ECHO_PACKET_DIRECTION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=188,
  serialized_end=290,
)


_ARGALI_PACKET = _descriptor.Descriptor(
  name='argali_packet',
  full_name='argali_packet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='payload_type', full_name='argali_packet.payload_type', index=0,
      number=1, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='logline', full_name='argali_packet.logline', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='echo', full_name='argali_packet.echo', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _ARGALI_PACKET_PACKET_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='msg', full_name='argali_packet.msg',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=293,
  serialized_end=470,
)

_LOGLINE.fields_by_name['level'].enum_type = _LOGLINE_LOGLEVEL
_LOGLINE_LOGLEVEL.containing_type = _LOGLINE
_ECHO_PACKET.fields_by_name['dir'].enum_type = _ECHO_PACKET_DIRECTION
_ECHO_PACKET_DIRECTION.containing_type = _ECHO_PACKET
_ARGALI_PACKET.fields_by_name['payload_type'].enum_type = _ARGALI_PACKET_PACKET_TYPE
_ARGALI_PACKET.fields_by_name['logline'].message_type = _LOGLINE
_ARGALI_PACKET.fields_by_name['echo'].message_type = _ECHO_PACKET
_ARGALI_PACKET_PACKET_TYPE.containing_type = _ARGALI_PACKET
_ARGALI_PACKET.oneofs_by_name['msg'].fields.append(
  _ARGALI_PACKET.fields_by_name['logline'])
_ARGALI_PACKET.fields_by_name['logline'].containing_oneof = _ARGALI_PACKET.oneofs_by_name['msg']
_ARGALI_PACKET.oneofs_by_name['msg'].fields.append(
  _ARGALI_PACKET.fields_by_name['echo'])
_ARGALI_PACKET.fields_by_name['echo'].containing_oneof = _ARGALI_PACKET.oneofs_by_name['msg']
DESCRIPTOR.message_types_by_name['logline'] = _LOGLINE
DESCRIPTOR.message_types_by_name['echo_packet'] = _ECHO_PACKET
DESCRIPTOR.message_types_by_name['argali_packet'] = _ARGALI_PACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

logline = _reflection.GeneratedProtocolMessageType('logline', (_message.Message,), dict(
  DESCRIPTOR = _LOGLINE,
  __module__ = 'argali_packet_pb2'
  # @@protoc_insertion_point(class_scope:logline)
  ))
_sym_db.RegisterMessage(logline)

echo_packet = _reflection.GeneratedProtocolMessageType('echo_packet', (_message.Message,), dict(
  DESCRIPTOR = _ECHO_PACKET,
  __module__ = 'argali_packet_pb2'
  # @@protoc_insertion_point(class_scope:echo_packet)
  ))
_sym_db.RegisterMessage(echo_packet)

argali_packet = _reflection.GeneratedProtocolMessageType('argali_packet', (_message.Message,), dict(
  DESCRIPTOR = _ARGALI_PACKET,
  __module__ = 'argali_packet_pb2'
  # @@protoc_insertion_point(class_scope:argali_packet)
  ))
_sym_db.RegisterMessage(argali_packet)


# @@protoc_insertion_point(module_scope)
